"""Public surface of the Label 309 standalone verifier."""

from __future__ import annotations

from .carriage import (
    TRANSPORT_CHUNK_MAX_BYTES,
    Label309ReassemblyFail,
    Label309ReassemblyOk,
    Label309ReassemblyResult,
    chunk_record_body,
    encode_label_309_value,
    reassemble_label_309_value,
)
from .cbor_walker import (
    MalformedTxCborError,
    TxComponents,
    UnwrappedAuxiliaryData,
    auxiliary_data_hash_from_tx_body,
    slice_tx_components,
    unwrap_auxiliary_data,
)
from .content_binding import CidBindingOutcome, ParsedCid, parse_cid, verify_ipfs_cid_binding
from .fetch import (
    ARWEAVE_GATEWAY_DEFAULTS,
    DEFAULT_OUTBOUND_MAX_BYTES,
    BodyTooLargeError,
    DenyHostError,
    OutboundExhaustedError,
    UnsupportedMethodError,
    UnsupportedProtocolError,
    default_fetch_outbound,
    matches_deny_list,
    wrap_fetch_outbound,
)
from .profile import detect_conformance_profile, out_of_profile_issues, profile_at_least
from .resolve import (
    BLOCKFROST_MAINNET_HOST,
    KOIOS_MAINNET_URL,
    ResolvedTx,
    ResolveFailure,
    ResolveOutcome,
    resolve_cardano_tx,
)
from .serialize import verify_report_to_dict
from .signatures import CARDANO_POE_SIG_DOMAIN_PREFIX, verify_record_signatures
from .tx_binding import TxBindingFail, TxBindingOk, TxBindingResult, bind_transaction_bytes
from .tx_witnesses import decode_tx_summary, decode_tx_witnesses
from .types import (
    BlockInfo,
    ContentCheck,
    Decryption,
    DecryptionOutcome,
    DecryptionPassphrase,
    DecryptionRecipient,
    ExitCode,
    FetchOutbound,
    FetchOutboundOptions,
    FetchOutboundResult,
    HttpCallRecord,
    Method,
    NetworkId,
    Profile,
    Purpose,
    SigFailureReason,
    SignatureVerdict,
    SignerType,
    Verdict,
    VerifierIssue,
    VerifierIssueCode,
    VerifyItemEntry,
    VerifyMerkleEntry,
    VerifyRecordInput,
    VerifyRecordSignature,
    VerifyReport,
    VerifyTxInput,
    VerifyTxOutput,
    VerifyTxSummary,
    VerifyTxWitness,
    exit_code_for_verdict,
)
from .verify import CONFIRMATION_DEPTH_THRESHOLD_DEFAULT, verify_record_bytes, verify_tx

# Universal loopback deny-host list a service-independent verifier MUST reject
# so a record can never be made to "verify" only because it reached a loopback
# address. This default carries no operator-specific entries: a deployment
# that wants to forbid its own gateway/viewer hosts appends those at
# construction time.
DENY_HOSTS_DEFAULT: tuple[str, ...] = ("localhost", "127.0.0.1")

__all__ = [
    "ARWEAVE_GATEWAY_DEFAULTS",
    "BLOCKFROST_MAINNET_HOST",
    "CARDANO_POE_SIG_DOMAIN_PREFIX",
    "CONFIRMATION_DEPTH_THRESHOLD_DEFAULT",
    "DEFAULT_OUTBOUND_MAX_BYTES",
    "DENY_HOSTS_DEFAULT",
    "KOIOS_MAINNET_URL",
    "TRANSPORT_CHUNK_MAX_BYTES",
    "BlockInfo",
    "BodyTooLargeError",
    "CidBindingOutcome",
    "ContentCheck",
    "Decryption",
    "DecryptionOutcome",
    "DecryptionPassphrase",
    "DecryptionRecipient",
    "DenyHostError",
    "ExitCode",
    "FetchOutbound",
    "FetchOutboundOptions",
    "FetchOutboundResult",
    "HttpCallRecord",
    "Label309ReassemblyFail",
    "Label309ReassemblyOk",
    "Label309ReassemblyResult",
    "MalformedTxCborError",
    "Method",
    "NetworkId",
    "OutboundExhaustedError",
    "ParsedCid",
    "Profile",
    "Purpose",
    "ResolveFailure",
    "ResolveOutcome",
    "ResolvedTx",
    "SigFailureReason",
    "SignatureVerdict",
    "SignerType",
    "TxBindingFail",
    "TxBindingOk",
    "TxBindingResult",
    "TxComponents",
    "UnsupportedMethodError",
    "UnsupportedProtocolError",
    "UnwrappedAuxiliaryData",
    "Verdict",
    "VerifierIssue",
    "VerifierIssueCode",
    "VerifyItemEntry",
    "VerifyMerkleEntry",
    "VerifyRecordInput",
    "VerifyRecordSignature",
    "VerifyReport",
    "VerifyTxInput",
    "VerifyTxOutput",
    "VerifyTxSummary",
    "VerifyTxWitness",
    "auxiliary_data_hash_from_tx_body",
    "bind_transaction_bytes",
    "chunk_record_body",
    "decode_tx_summary",
    "decode_tx_witnesses",
    "default_fetch_outbound",
    "detect_conformance_profile",
    "encode_label_309_value",
    "exit_code_for_verdict",
    "matches_deny_list",
    "out_of_profile_issues",
    "parse_cid",
    "profile_at_least",
    "reassemble_label_309_value",
    "resolve_cardano_tx",
    "slice_tx_components",
    "unwrap_auxiliary_data",
    "verify_ipfs_cid_binding",
    "verify_record_bytes",
    "verify_record_signatures",
    "verify_report_to_dict",
    "verify_tx",
    "wrap_fetch_outbound",
]
