from __future__ import annotations

from .fetch import (
    DEFAULT_OUTBOUND_MAX_BYTES,
    BodyTooLargeError,
    ContentUnavailableError,
    DenyHostError,
    OutboundExhaustedError,
    UnsupportedMethodError,
    UnsupportedProtocolError,
    UriTargetForbiddenError,
    default_fetch_outbound,
    fetch_item_ciphertext,
    wrap_fetch_outbound,
)
from .merkle import check_merkle_commitments
from .profile import out_of_profile_issues, profile_at_least
from .resolve import (
    BLOCKFROST_MAINNET_HOST,
    KOIOS_MAINNET_URL,
    NotALabel309RecordError,
    ResolvedTx,
    extract_label_309_metadata,
    resolve_cardano_tx,
)
from .serialize import verify_report_to_dict
from .signatures import CARDANO_POE_SIG_DOMAIN_PREFIX, verify_record_signatures
from .types import (
    VERIFIER_ONLY_ERROR_CODES,
    Decryption,
    DecryptionFailureReason,
    DecryptionPassphrase,
    DecryptionRecipient,
    DecryptionVerdict,
    ExitCode,
    FetchOutbound,
    FetchOutboundOptions,
    FetchOutboundResult,
    HttpCallRecord,
    ItemHashCheck,
    MerkleCheckReason,
    MerkleVerdict,
    Method,
    NetworkId,
    Profile,
    Purpose,
    SigFailureReason,
    SignatureVerdict,
    SignerType,
    SupersedesResolved,
    UriFailureReason,
    ValidationSummary,
    Verdict,
    VerifierIssue,
    VerifierIssueCode,
    VerifyItemDecryption,
    VerifyMerkleCheck,
    VerifyRecordSignature,
    VerifyReport,
    VerifyTxInput,
    VerifyTxOutput,
    VerifyTxSummary,
    VerifyTxWitness,
    VerifyUriCheck,
)
from .verify import CONFIRMATION_DEPTH_THRESHOLD_DEFAULT, verify_tx

# Default deny-host floor. Single-implementer domains (cardanowall.com et
# al.) must remain deny-able WITHOUT breaking the verification of any
# conformant record; the conformance suite proves service-independence by
# running with this list active.
DENY_HOSTS_DEFAULT: tuple[str, ...] = (
    "cardanowall.com",
    "*.cardanowall.com",
    "localhost",
    "127.0.0.1",
)

__all__ = [
    "BLOCKFROST_MAINNET_HOST",
    "CARDANO_POE_SIG_DOMAIN_PREFIX",
    "CONFIRMATION_DEPTH_THRESHOLD_DEFAULT",
    "DEFAULT_OUTBOUND_MAX_BYTES",
    "DENY_HOSTS_DEFAULT",
    "KOIOS_MAINNET_URL",
    "VERIFIER_ONLY_ERROR_CODES",
    "BodyTooLargeError",
    "ContentUnavailableError",
    "Decryption",
    "DecryptionFailureReason",
    "DecryptionPassphrase",
    "DecryptionRecipient",
    "DecryptionVerdict",
    "DenyHostError",
    "ExitCode",
    "FetchOutbound",
    "FetchOutboundOptions",
    "FetchOutboundResult",
    "HttpCallRecord",
    "ItemHashCheck",
    "MerkleCheckReason",
    "MerkleVerdict",
    "Method",
    "NetworkId",
    "NotALabel309RecordError",
    "OutboundExhaustedError",
    "Profile",
    "Purpose",
    "ResolvedTx",
    "SigFailureReason",
    "SignatureVerdict",
    "SignerType",
    "SupersedesResolved",
    "UnsupportedMethodError",
    "UnsupportedProtocolError",
    "UriFailureReason",
    "UriTargetForbiddenError",
    "ValidationSummary",
    "Verdict",
    "VerifierIssue",
    "VerifierIssueCode",
    "VerifyItemDecryption",
    "VerifyMerkleCheck",
    "VerifyRecordSignature",
    "VerifyReport",
    "VerifyTxInput",
    "VerifyTxOutput",
    "VerifyTxSummary",
    "VerifyTxWitness",
    "VerifyUriCheck",
    "check_merkle_commitments",
    "default_fetch_outbound",
    "extract_label_309_metadata",
    "fetch_item_ciphertext",
    "out_of_profile_issues",
    "profile_at_least",
    "resolve_cardano_tx",
    "verify_record_signatures",
    "verify_report_to_dict",
    "verify_tx",
    "wrap_fetch_outbound",
]
