"""Checksummed string encoding for the 32-byte identity seed.

The display/generation form is classic BIP-173 bech32 (no length limit -- the
same primitive the age-style recipient codec uses) under the HRP
``l309-seed-``, returned UPPERCASE: ``L309-SEED-1...``. Secrets are loud: the
uppercase form is visually unmistakable next to lowercase recipient addresses
(``age1...``, ``age1pqc...``), mirroring age's ``AGE-SECRET-KEY-1...``
convention, and the checksum deterministically catches typos and truncation.

Parsing accepts two representations:

1. the bech32 form in all-lowercase or all-uppercase (mixed case is rejected
   per BIP-173), checksum verified, HRP exactly ``l309-seed-``, payload exactly
   32 bytes;
2. raw hex -- 64 hex digits, case-insensitive, tolerating a ``0x`` prefix and
   surrounding/internal whitespace -- the lowest-common-denominator interchange
   form, so a seed generated by any external tool imports.

Byte-identical parity twin of ``@cardanowall/crypto-core``'s
``encodeIdentitySeed`` / ``parseIdentitySeed``.
"""

from __future__ import annotations

import re
from typing import Final

from .recipient import _bech32_decode_no_limit, bech32_encode_no_limit

# The bech32 human-readable part. The trailing hyphen is part of the HRP, so
# with the bech32 separator `1` the rendered prefix reads `l309-seed-1...`.
IDENTITY_SEED_HRP: Final[str] = "l309-seed-"

_SEED_LENGTH: Final[int] = 32
_SEED_HEX_DIGITS: Final[int] = 64
_HEX_BODY: Final[re.Pattern[str]] = re.compile(r"[0-9a-fA-F]+")
# ASCII-case-insensitive probe: does the input claim to be the bech32 form?
# Decides whether a decode failure is reported as a corrupted seed string
# (SEED_STRING_BAD_CHECKSUM) or as unrecognized input. re.ASCII keeps
# IGNORECASE from Unicode-case-folding a non-ASCII character into the prefix.
_CLAIMS_SEED_PREFIX: Final[re.Pattern[str]] = re.compile(r"l309-seed-1", re.IGNORECASE | re.ASCII)
_ASCII_LOWER: Final[re.Pattern[str]] = re.compile(r"[a-z]")
_ASCII_UPPER: Final[re.Pattern[str]] = re.compile(r"[A-Z]")


class SeedEncodingError(Exception):
    """Raised by the identity-seed string codec.

    The codes are the cross-implementation contract: every conforming
    implementation rejects the same malformed input with the same code.
    """

    INVALID_SEED_LENGTH = "INVALID_SEED_LENGTH"
    SEED_STRING_MIXED_CASE = "SEED_STRING_MIXED_CASE"
    SEED_STRING_BAD_CHECKSUM = "SEED_STRING_BAD_CHECKSUM"
    SEED_STRING_WRONG_HRP = "SEED_STRING_WRONG_HRP"
    SEED_STRING_WRONG_LENGTH = "SEED_STRING_WRONG_LENGTH"
    SEED_STRING_UNRECOGNIZED = "SEED_STRING_UNRECOGNIZED"

    def __init__(self, code: str, message: str) -> None:
        super().__init__(f"{code}: {message}")
        self.code: str = code


def encode_identity_seed(seed: bytes) -> str:
    """Encode a 32-byte identity seed to its checksummed display form.

    Returns the UPPERCASE string ``L309-SEED-1...`` (~69 characters). Raises
    :class:`SeedEncodingError` (``INVALID_SEED_LENGTH``) unless the seed is
    exactly 32 bytes.
    """
    if len(seed) != _SEED_LENGTH:
        raise SeedEncodingError(
            SeedEncodingError.INVALID_SEED_LENGTH,
            f"seed must be exactly 32 bytes, got {len(seed)}",
        )
    return bech32_encode_no_limit(IDENTITY_SEED_HRP, seed).upper()


def parse_identity_seed(text: str) -> bytes:
    """Parse an identity seed from either accepted representation.

    Accepts the checksummed bech32 form in a single case, or 64-digit raw hex;
    returns the 32 raw seed bytes. The inverse of :func:`encode_identity_seed`
    for the bech32 form. Raises :class:`SeedEncodingError` with the code naming
    what was wrong: a mixed-case bech32 string, a failed checksum, a foreign
    HRP (e.g. an age recipient pasted by mistake), a wrong payload or hex-digit
    length, or input that is neither representation.
    """
    # Hex path: strip ALL whitespace and an optional 0x prefix; if what remains
    # is pure hex it can only be meant as a hex seed (the bech32 form always
    # carries non-hex characters: the HRP's `l`, `s`, and `-`).
    compact = "".join(text.split())
    hex_body = compact[2:] if compact[:2] in ("0x", "0X") else compact
    if hex_body and _HEX_BODY.fullmatch(hex_body):
        if len(hex_body) != _SEED_HEX_DIGITS:
            raise SeedEncodingError(
                SeedEncodingError.SEED_STRING_WRONG_LENGTH,
                f"hex seed must be exactly 64 hex digits, got {len(hex_body)}",
            )
        return bytes.fromhex(hex_body)

    # Bech32 path: a single token, so only surrounding whitespace is tolerated.
    candidate = text.strip()
    claimed = _CLAIMS_SEED_PREFIX.match(candidate) is not None
    if claimed and _ASCII_LOWER.search(candidate) and _ASCII_UPPER.search(candidate):
        raise SeedEncodingError(
            SeedEncodingError.SEED_STRING_MIXED_CASE,
            "identity-seed string mixes upper and lower case; use one case only",
        )
    try:
        hrp, payload = _bech32_decode_no_limit(candidate)
    except ValueError as cause:
        if claimed:
            raise SeedEncodingError(
                SeedEncodingError.SEED_STRING_BAD_CHECKSUM,
                "identity-seed string failed bech32 decoding "
                "(checksum, character set, or structure)",
            ) from cause
        raise SeedEncodingError(
            SeedEncodingError.SEED_STRING_UNRECOGNIZED,
            "expected a 64-hex-digit seed or an L309-SEED-1... string",
        ) from cause
    if hrp != IDENTITY_SEED_HRP:
        raise SeedEncodingError(
            SeedEncodingError.SEED_STRING_WRONG_HRP,
            f'expected the bech32 prefix "{IDENTITY_SEED_HRP}", got "{hrp}"',
        )
    if len(payload) != _SEED_LENGTH:
        raise SeedEncodingError(
            SeedEncodingError.SEED_STRING_WRONG_LENGTH,
            f"identity-seed payload must be exactly 32 bytes, got {len(payload)}",
        )
    return payload


__all__ = [
    "IDENTITY_SEED_HRP",
    "SeedEncodingError",
    "encode_identity_seed",
    "parse_identity_seed",
]
